language: ruby
rvm:
  - 2.3.3
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install: gem install bundler -v 1.13.6
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_success: bundle exec codeclimate-test-reporter
env:
  global:
    - APP_ENV=test
    - DATABASE_URL=postgres://localhost:5432/travis_ci_test
