module Agilizer
  module Client
    module Presenters

      # Presenter for issue statistics generated by
      # `IssueAnalysis::Statistics.calculate`
      #
      # statistics are expected to follow this format:
      #     type (timespent, time_estimate...)
      #   > role (developer, reviewer...)
      #   > team_member
      class IssueStatistics

        def initialize(statistics)
          @statistics = statistics
        end

        # Extract team members from statistics.
        def team_members
          @statistics.map do |type, statistics_by_type|
            statistics_by_type.values.map(&:keys).flatten
          end.flatten.uniq
        end

        def get(type, role, team_member)
          seconds = @statistics[type][role][team_member]
          hours = (seconds / 3600.to_f).round(1)
        end
      end
    end
  end
end
