base: &default
  clients:
    default:
      uri: <%= ENV['AGILIZER_MONGODB_URI'] %>

production:
  <<: *default

development:
  <<: *default

test:
  clients:
    default:
      uri: <%= ENV['AGILIZER_MONGODB_URI'] %>_test
      safe: true
