#!/usr/bin/env ruby
#
# Process all Issue records to fetch code changes
# from Github according to the pull request information
# in the issue.
#
# Uses the `Agilizer::Enrichments::SourceCodeChange` module.
#
# Usage:
#   bin/apply_enrichments

# Load dependencies
require "rubygems"
require "bundler/setup"

$LOAD_PATH.unshift File.expand_path("../..", __FILE__)
require "config/boot"

require "agilizer/enrichments/source_code_changes"
Agilizer::Enrichments::SourceCodeChanges.run_for_applicable_issues
