#!/usr/bin/env ruby

# Delete all Agilizer data (but not source data cached, like
# JiraCache's and TogglCache's).
#
# To rebuild all Agilizer data from the caches, you may use
# this script: `scripts/process_cache`.
#
# Usage:
#     bin/clear_agilizer

# Load dependencies
require "rubygems"
require "bundler/setup"

$LOAD_PATH.unshift File.expand_path("../..", __FILE__)
require "config/boot"

require "agilizer/data/issue_repository"
Agilizer::Data::IssueRepository.delete_where(true)
