#!/usr/bin/env ruby

# Clear cache and performs a full sync.
#
# Usage:
#     script/clear_jira_cache

# Load dependencies
require "rubygems"
require "bundler/setup"

$LOAD_PATH.unshift File.expand_path("../..", __FILE__)
require "config/boot"

require "jira_cache/data/issue_repository"
JiraCache::Data::IssueRepository.delete_where("TRUE")
