#!/usr/bin/env ruby

# Fetch new content from the different integrations.
#
# Currently:
#   - import JIRA issues,
#   - import Toggl reports.
#
# The synchronization is built to be run regularly.
# It should be scheduled using a _crontab_ or similar
# mechanism (e.g. Heroku Scheduler add-on).
#
# NB: for the initial import, the `script/import` script
# must be used.
#
# Usage:
#     script/sync

require "rubygems"
require "bundler/setup"

$LOAD_PATH.unshift File.expand_path("../..", __FILE__)
require "config/boot"

require "logger"
logger = Logger.new(STDOUT)
logger.level = Logger.const_get(ENV["JIRA_LOG_LEVEL"].to_sym)

########
# JIRA #
########

require "agilizer/interface/jira"
jira_interface = Agilizer::Interface::JIRA.new(logger: logger)
jira_interface.import_all

# Cleanup issues deleted from JIRA
require "jira_cache/data/issue_repository"
deleted_issue_keys = JiraCache::Data::IssueRepository.keys_for_deleted_issues
Agilizer::Data::IssueRepository.delete_where(identifier: deleted_issue_keys)
logger.info "Deleted issues for the following identifiers: #{deleted_issue_keys}"

#########
# Toggl #
#########

require "agilizer/interface/toggl"
toggl_interface = Agilizer::Interface::Toggl.new(logger: logger)
toggl_interface.import_all
