#!/usr/bin/env ruby

# Fetches new and updated issues from the sources,
# processes them and saves them as Issue records.
#
# Usage:
#     script/sync

# Load dependencies
require "rubygems"
require "bundler/setup"

$LOAD_PATH.unshift File.expand_path("../..", __FILE__)
require "config/boot"

require "logger"
logger = Logger.new(STDOUT)
logger.level = Logger.const_get(ENV["JIRA_LOG_LEVEL"].to_sym)

require "agilizer/interface/jira"
jira_interface = Agilizer::Interface::JIRA.new(logger: logger)
jira_interface.import_all

# Cleanup issues deleted from JIRA
require "jira_cache/data/issue_repository"
deleted_issue_keys = JiraCache::Data::IssueRepository.keys_for_deleted_issues
Agilizer::Data::IssueRepository.delete_where(identifier: deleted_issue_keys)
logger.info "Deleted issues for the following identifiers: #{deleted_issue_keys}"
